platform	:ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

# Third Party Pods
# End Third Party Pods

#--BEGIN LOCAL In-House Dependencies
podLocal = ENV['POD_LOCAL_HOME']
#--END LOCAL In-House Dependencies

#--BEGIN RELEASED In-House Dependencies
#--END RELEASED In-House Dependencies
